version: "3.3"

# For development

services:
  vue-frontend:
    container_name: tithe-vue-frontend
    image: tithe-vue-frontend-image
    build: ./Tithe-Vue/
    ports:
      - 80:80
    restart: always
    depends_on:
      - spring-backend

  spring-backend:
    container_name: tithe-spring-backend
    image: tithe-spring-backend-image
    build: ./Tithe-Spring/
    #volumes:
      #- ./Tithe-Spring:/spring
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgresql-db

  postgresql-db:
    container_name: postgres-db
    image: 'postgres'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
#    volumes:
#      - ./postgres-volume:/var/lib/postgresql/data:z
