version: "3.3"

services:
  postgresql-db:
    container_name: postgres-db
    image: 'postgres'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
#    volumes:
#      - ./postgres-volume:/var/lib/postgresql/data:z
