spring:
  datasource:
    url: jdbc:postgresql://postgresql-db:5432/postgres
  graphql:
    cors:
      allowed-origins:
        - http://localhost:5173/
        - http://localhost
        - http://127.0.0.1:5173/
        - http://127.0.0.1
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
