spring:
  datasource:
    url: jdbc:postgresql://postgresql-db:5432/postgres
  graphql:
    cors:
      allowed-origins:
        - http://13.53.86.195
        - http://13.53.86.195:4173
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
