spring:
  datasource:
    url: jdbc:postgresql://postgresql-db:5432/postgres
  graphql:
    cors:
      allowed-origins:
        - http://16.171.119.189
        - http://16.171.119.189:4173
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
