name: Release Asset on Push

on:
  push:
    branches:
      - dev

jobs:
  
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: temurin
        
      - name: Move files from Spring root folder to working directory
        run: mv $GITHUB_WORKSPACE/Tithe-Spring/* $GITHUB_WORKSPACE/
      
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
  
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    needs: build
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: temurin
        
      - name: Move files from Spring root folder to working directory
        run: mv $GITHUB_WORKSPACE/Tithe-Spring/* $GITHUB_WORKSPACE/
      
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
      
      - name: Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          files: ./build/libs/*.jar
