name: Deploy to stage environment

on:
  push:
    branches:
      - "stage"

jobs:

  build:
    uses: ./.github/workflows/build.yml

  deploy:
    runs-on: ubuntu-latest
    environment: stage
    permissions:
      contents: write
      
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
    
      # - name: Get Github Runner IP
      #   id: ip
      #   uses: haythem/public-ip@v1.3

      # - name: AWS Configure
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      # - name: Add Github Runner IP to Security Group
      #   env:
      #     AWS_SECURITY_GROUP_ID: ${{ secrets.AWS_SECURITY_GROUP_ID }}
      #   run: |
      #     aws ec2 authorize-security-group-ingress --group-id ${{ env.AWS_SECURITY_GROUP_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/16
      #     sleep 10

      - name: Deploy on AWS EC2
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_EC2_SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.AWS_EC2_HOSTNAME }}
          REMOTE_USER: ${{ secrets.AWS_EC2_USERNAME }}
          TARGET: "~/"
          EXCLUDE: "/dist/, /node_modules/"
          SCRIPT_BEFORE: |
            ls -a
            sudo apt-get update -y
            sudo apt-get upgrade -y
          SCRIPT_AFTER: |
            ls -a
            sudo chmod +x ./stage-deploy.sh
            ./stage-deploy.sh
